- block:
    - name: Ensure Xvfb package
      apt: name="{{ item }}"
      with_items:
        - xserver-xorg-core
        - xvfb

    - name: Ensure firefox-{{ ansible_architecture }} v{{ firefox_version }}
      shell: |
        firefox --version | grep -F '{{ firefox_version }}' && exit 0

        mkdir -p /opt
        curl https://download-installer.cdn.mozilla.net/pub/firefox/releases/{{ firefox_version }}/linux-{{ ansible_architecture }}/en-US/firefox-{{ firefox_version }}.tar.bz2 | tar -jx -C /opt
        [[ -L /usr/bin/firefox ]] && rm /usr/bin/firefox
        [[ -f /usr/bin/firefox ]] && mv /usr/bin/firefox /usr/bin/firefox-orig
        ln -s /opt/firefox/firefox /usr/bin/firefox
        ln -s /opt/firefox/firefox /usr/bin/firefox-{{ firefox_version }}
      args:
        creates: "/usr/bin/firefox-{{ firefox_version }}"

    - name: Xvfb:{{ xvfb.display }} init.d script
      template: src=init_xvfb.sh.j2 dest=/etc/init.d/xvfb mode="0755"
      notify: Restart and enable xvfb service

    - name: Xvfb:{{ xvfb.display }} profile
      copy:
        dest: /etc/profile.d/xvfb.sh
        content: |
          export DISPLAY=:{{ xvfb.display }}
      notify: Restart and enable xvfb service

  when: ansible_os_family == "Debian"
