- block:
    - name: Ensure Xvfb package
      apt: name="{{ item }}"
      with_items:
        - xserver-xorg-core
        - xvfb
        - firefox

    - name: Xvfb:{{ xvfb.display }} init.d script
      template: src=init_xvfb.sh.j2 dest=/etc/init.d/xvfb mode="0755"
      notify: Restart xvfb service

    - name: Xvfb:{{ xvfb.display }} profile
      copy:
        dest: /etc/profile.d/xvfb.sh
        content: |
          export DISPLAY=:{{ xvfb.display }}

    - name: Ensure xvfb service is running
      service: name=xvfb state=started

  when: ansible_os_family == "Debian"
