---
- block:
    - name: Install add-apt-repostory
      apt: name=software-properties-common state=latest

    - name: Add Oracle Java Repository
      apt_repository: repo='ppa:webupd8team/java'

    - name: Accept Java 8 License
      debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

    - name: Install Oracle Java 8
      apt: name={{item}} state=latest
      with_items:
        - oracle-java8-installer
        - ca-certificates
        - oracle-java8-set-default

    - name: JDK profile
      copy:
        dest: "{{ jdk8.profile }}"
        content: |
          export JAVA_HOME="/usr/lib/jvm/java-8-oracle"
          export PATH="$JAVA_HOME/bin:$PATH"
  when: ansible_os_family == "Debian"

